### ISSUE TITLE
Add optional prefix config variable

### ISSUE THREAD

**Issue by pnbruckner** [pnbruckner/ha-sun2#1]
E.g.:
```text
sensor:
  - platform: sun2
    monitored_conditions: [daylight, sunrise, sunset]
    prefix: solar
```
Which results in:
```text
sensor.solar_daylight
sensor.solar_sunrise
sensor.solar_sunset
```

**Comment by pnbruckner** [comment]
Actually, discovered that there is already a standard way to do this:
```text
sensor:
  - platform: sun2
    monitored_conditions: [daylight, sunrise, sunset]
    entity_namespace: solar
```
per https://www.home-assistant.io/docs/configuration/platform_options/#entity-namespace

**Comment by cowboysdude** [comment]
Excuse my ignorance but I have the `sensor: !include_dir_merge_list includes/sensors/` in my config and I need to create an actual sensor and have tried several different ways but it says no.   

I've tried this and nope....

`- platform: sun2
  sensors:
    monitored_conditions: [dawn, sunrise, sunset, dusk, daylight, night, elevation, min_elevation, max_elevation, sun_phase]
    entity_namespace: solar `

Config validation fails....... so I'm at a loss as to how create a sun2.yaml file for this to create a sensor....  Any help would be appreciated!!

Error:  `Invalid config for [sensor.sun2]: [sensors] is an invalid option for [sensor.sun2]. Check: sensor.sun2->sensors.`

**Comment by pnbruckner** [comment]
@cowboysdude if you're asking for help with the sun2 sensor you should open a new issue, not tack on to the end of a closed one. Also, what you're asking really isn't about the sun2 sensor, but rather how to use advanced methods of splitting up your configuration, specifically how to use [include_dir_merge_list](https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-include_dir_merge_list). For that you should use the Home Assistant Community Forum or Discord. In the future please use an appropriate method when asking for help.

But to answer your question, given having `ensor: !include_dir_merge_list includes/sensors/` in your config, and you put sun2.yaml in includes/sensors, then it should probably contain the following:
```yaml
- platform: sun2
  monitored_conditions: [dawn, sunrise, sunset, dusk, daylight, night, elevation, min_elevation, max_elevation, sun_phase]
  entity_namespace: solar
```
