### ISSUE TITLE
Sunrise and Sunset sensors not created after upgrading to v3.0.0

### ISSUE THREAD

**Issue by kaizersoje** [pnbruckner/ha-sun2#101]
After upgrading to v3.0.0, I noticed the sunrise and sunset sensors have not been created. I can only see the integration creates only the following sensors by default.

![image](https://github.com/pnbruckner/ha-sun2/assets/54566217/7289cd17-b3ae-49b4-abcb-de323556cf35)

**Comment by RedNo7** [comment]
Same here.

**Comment by pnbruckner** [comment]
The entity IDs will not be identical to what they were before. If you need the older entity IDs, you can change them from the settings for each entity.

Per the documentation, there are many entities that are created automatically, but most will be disabled by default. If the default set (which is similar to the built-in sun integration) is not what you want, go to the Devices & services page, view the entities for the Sun2 integration, and enable/disable the entities as desired.

**Comment by RedNo7** [comment]
I think the OP is not referring to the start of the new entity_id (eg: `sensor.sun...` becoming `sensor.test_sun...`, but the end where `...sunset` has become `...sun_setting`

**Comment by pnbruckner** [comment]
@kaizersoje has your issue been resolved? Or do you have further questions?

**Comment by kaizersoje** [comment]
Yes @pnbruckner
