### ISSUE TITLE
Deprecated constant DEVICE_CLASS_TIMESTAMP willbe removed in HA Core 2025.1

### ISSUE THREAD

**Issue by override80** [pnbruckner/ha-sun2#107]
WARNING:homeassistant.const:DEVICE_CLASS_TIMESTAMP was used from sun2, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TIMESTAMP instead, please create a bug report at https://github.com/pnbruckner/ha-sun2/issues

**Comment by pnbruckner** [comment]
Thanks.

**Comment by pnbruckner** [comment]
@override80, what version of the Sun2 integration are you using? It must be pretty old, because that was changed in release 2.2.0 over a year ago.

**Comment by override80** [comment]
My bad! That's what happens when you manually install  a custom component without hacs and it works flawlessly for months :)
