### ISSUE TITLE
Elevation stopped working

### ISSUE THREAD

**Issue by oneseventhree** [pnbruckner/ha-sun2#114]
Hi,

I swapped from YAML to UI config after HA's latest update said I had to and now my elevation is no longer updating.

If I restart HA the elevation updates but then stays stuck on that until I restart again.

How can I fix this?

Thanks!

**Comment by pnbruckner** [comment]
Some details would be helpful.

- What version of HA Core were you using before the update and what version are you using now?
- What version of this custom integration were you using before the update and what version are you using now?
- What exactly do you mean by, "HA's latest update said" you had to swap from YAML to UI config? Was there an error message or some other indication, and exactly what did it say?

This custom integration does not require UI configuration. It still supports YAML based configuration, so there should have been no reason to switch to UI based configuration.

Having said that, either way the elevation sensor should not just stop working. Once I get more details from you, I can try to diagnose the problem. At some point I may need your location details so I can reproduce the problem. If so, you can send me those privately.

**Comment by pnbruckner** [comment]
My guess is that you still have `sun2` configured under `sensor` and/or `binary_sensor`, which was deprecated about four months ago in the 3.0.0 release. However, YAML configuration is still supported under `sun2` itself. Details were provided in the 3.0.0 documentation: https://github.com/pnbruckner/ha-sun2/tree/3.0.0#converting-from-platform-configuration.

**Comment by oneseventhree** [comment]
Thanks for that! After a restart of HA and deleting the old entities it started working again :)
