### ISSUE TITLE
A lot of  entities are not available with the UI integraiton

### ISSUE THREAD

**Issue by SeByDocKy** [pnbruckner/ha-sun2#115]
I had to be forced to pass trough the UI, with a error saying sensors.yaml  configuration is no more accepted

``- platform: sun2
  monitored_conditions:
    - daylight
    - civil_daylight
    - nautical_daylight
    - astronomical_daylight
``
These entities are no more available for example

**Comment by SeByDocKy** [comment]
> > I had to be forced to pass trough the UI, with a error saying sensors.yaml configuration is no more accepted
> 
> Can you please share the exact message? This integration still supports YAML configuration.
> 
> Also, what version of HA Core and what version of this custom integration are you using where you got this error?
> 
> Yes, all the sensors are still available when using UI-based configuration. Many are disabled by default. You just need to enable the ones you want. This is all documented.

```Core
2024.2.5
Supervisor
2024.02.1
Operating System
12.0
Interface utilisateur
20240207.1
```

Yes there are written as disabled.... but I can't find how to (re) enable them

**Comment by pnbruckner** [comment]
No problem.

The older style YAML configuration with `sun2` under `platform` was deprecated about four months ago in the 3.0.0 release. However, YAML configuration is still supported under `sun2` itself. Details were provided in the 3.0.0 documentation: https://github.com/pnbruckner/ha-sun2/tree/3.0.0#converting-from-platform-configuration.
