### ISSUE TITLE
HACS 1.6 Compliant

### ISSUE THREAD

**Issue by teamsuperpanda** [pnbruckner/ha-sun2#14]
Had an error trying to add the repository to HACS.
Error suggested it isn't 1.6 compliant.

Adding the repository:
https://github.com/pnbruckner/ha-sun2

<img width="459" alt="Screen Shot 2020-04-21 at 10 47 23 AM" src="https://user-images.githubusercontent.com/60556240/79807022-e3ac5100-83bd-11ea-8830-7124c52b19a5.png">
<img width="982" alt="Screen Shot 2020-04-21 at 10 47 26 AM" src="https://user-images.githubusercontent.com/60556240/79807028-e60eab00-83bd-11ea-811d-03cca4bfea26.png">

**Comment by pnbruckner** [comment]
I don't use HACS, and I gave up long ago trying to keep up with all its changing requirements. If you'd like to figure out how to make it work and submit a PR, I'll consider it.
