### ISSUE TITLE
Allow in automations to specify template for offset

### ISSUE THREAD

**Issue by vekexasia** [pnbruckner/ha-sun2#16]
Hello, as requested https://github.com/home-assistant/core/issues/30761 It would be extremely helpful to have a way to specify the offset via a template in automation triggered by sunrise/sunset events with a time skew that might be depending on the value of another sensor..

**Comment by pnbruckner** [comment]
Oh, ok, I think I understand now what was being asked for with `after_offset_template` and `before_offset_template`. I didn't realize that was for sun triggers, which is an `automation` thing, not a `sun` integration thing. So that doesn't apply here either. Sorry for the confusion.
