### ISSUE TITLE
High CPU Load

### ISSUE THREAD

**Issue by Nesie** [pnbruckner/ha-sun2#20]
Hi, 

 If I use your nice Integration on my Dashboard within a browser on a remote raspberry pi 3. I face an very high cpu load for it. 
For trying to get an evidence that it comes realy from ha-sun2, I put the integration onto a new blank tab Page as the only element and all Time I switch onto that tab the Raspberry CPU load is going up to 75% - 90%. If I switch back to other Stuff on parallel Pages e.g. Weather or mini media panel it is alway goes down to less then 5% to 10% of CPU load.
If I let the browser window on that tab with your integration, CPU load raises until the raspberry shows up a temperatur alarm on the upper right corner.
I did no special configuration for the configuration on lovelace:

   entities:
      max_elevation: sun.sun
      moon: sensor.moon
      noon: sensor.solar_noon
      sunrise: sensor.sunrise
      sunset: sensor.sunset
     meridiem: false
     name: Sonnenstand
  type: 'custom:sun-card'

Do someone have the same behavier or a hint to prevent it ?

**Comment by pnbruckner** [comment]
I have no idea what might cause that. That is a frontend issue, and it looks like you're using some custom card that I had nothing to do with. All my code runs in the backend and would have nothing directly to do with browser CPU load. I suggest you contact the author of the custom sun-card.
