### ISSUE TITLE
Getting an "integration not found"-error on HA 0.111.4 and 0.114.2

### ISSUE THREAD

**Issue by ars4l4n** [pnbruckner/ha-sun2#26]
Had [this error](https://i.imgur.com/THCqiP7.png) before and after updating to the latest homeassistant version

your old sun component doesn't work either (don't get an error for it though)
followed the instructions precisely
What could be the issue?

**Comment by pnbruckner** [comment]
That is just a picture of available HA updates, not errors. Did you post the wrong picture?

> your old sun component doesn't work either

I'm not surprised, and it's not supported anymore anyway.

I'm using this custom integration with 0.113.3. I haven't upgrade to 0.114 yet. If you can post error messages I can take a look.

**Comment by ars4l4n** [comment]
sorry, I actually meant this picture https://i.imgur.com/M5tRQ3W.png ^^"""

**Comment by ars4l4n** [comment]
That baffles me. I tried reinstalling by deleting all sun2 folders including costum_components, rebooting, placing new copies of the 5 installation files into the correct path. I got the files via right clicking "RAW"->"save link as" on github.
I then rebooted again, [a post on the HA forums](https://community.home-assistant.io/t/enhanced-sun-component/63553/381?u=ars4l4n) suggested that if I understood him correctly. He didn't answer precisely though.
Is that what you meant in an [earlier post when you said you have to stop HA before installing a costum component](https://community.home-assistant.io/t/enhanced-sun-component/63553/369

)?
Because when HA is stopped I can't use the file editor to use install the costum component

If you have no other suggestions, perhaps you may load up the partial HA backup I created
https://drive.google.com/file/d/1KAtKhdBZbTFYhTpp547vHdjQr82rDkTQ/view?usp=sharing

**Comment by pnbruckner** [comment]
You are constrained by the installation method you chose. I don't use that so I can't help precisely. But in general, what David meant was, remove all sun2 related items from your configuration. Then restart so the sun2 files are not being used. Now you can update or add the sun2 files in the config/custom_components folder. Now restart again. Now you can add sun2 related items to your config, which probably requires another restart to take effect. There may be some shortcuts, but if you do that it _should_ work. Using the sun2 custom integration is just like using any other custom integration. There are no special requirements here.

**Comment by ars4l4n** [comment]
I had followed all the steps before, I did use the hassio.host_reboot
service though and not ha core restart which seems to be what you meant.
Now I've read that another user who had this error when installing a
costum component solved it by "restarting the service via the command line
instead of using the restart from the web console" (link
<(https://community.home-assistant.io/t/solved-cant-install-custom-component/52692/5?u=ars4l4n)>
)
I wasn't sure if that meant that you have to plug a keyboard to your PI and
do it via the terminal there or if the SSH terminal via the homeassistant
web interface was okay too.
I did both methods using ha core restart between each step.
At the beginning I also deleted all sun2 files + configurations, did ha
core restart *and *ha host reboot
and after everything was done I did ha core restart *and *ha host reboot
Still the same error though. Would that even have possibly made any
difference?

Deleted sun2 sensors in config.yaml, ha restart, added a space
plus -rw-r--r-- to the name of the python files in the sun2 folder, ha
restart, same result

I tried writing the sun2 sensor into the bottom of the list of my sensors
in the config.yaml file instead of the top (because once I had that issue
that for some reason when I repositioned it even though the spaces were
correct before it worked all of a sudden when it didn't before) - no success

What now?

Am Do., 20. Aug. 2020 um 21:48 Uhr schrieb Phil Bruckner <
notifications@github.com>:

**Comment by pnbruckner** [comment]
Sorry, I can't help you. Like I said, this custom integration is no different than any other custom integration with regards to installing it. I suggest you ask for help on the HA community forum or discord chat.

**Comment by ars4l4n** [comment]
What installation method do you actually use? I tried doing it via File Editor and now also via Samba
And What kind of host are you on? I use a Raspberry Pi 3.

**Comment by marc-maurer** [comment]
@pnbruckner issue seems to be resolved, close it?
