### ISSUE TITLE
Elevation stops updating

### ISSUE THREAD

**Issue by Zendio** [pnbruckner/ha-sun2#27]
Just recently I noticed that the elevation sensor doesn't update regularly anymore, which is breaking automations that use the sensor. 

Right now it's 9 AM and the sun is above the horizon, but it tells me that the next update is in the afternoon and the sun is below the horizon. I haven't changed any configuration, other than updating HA to the latest version. After rebooting HA it works again for about a day, before it stops updating regularly again. 

![CleanShot 2021-01-27 at 08 59 37](https://user-images.githubusercontent.com/5435734/105960895-23efdc80-607e-11eb-9988-375d694c7e1b.png)

**Comment by dynasticorpheus** [comment]
Noticed the same

**Comment by pnbruckner** [comment]
@Zendio @dynasticorpheus 

Sorry I haven't had much time for HA these days. Are you seeing any error messages, especially any exceptions?

You can enable debug logging for this custom integration using:

```
logger:
  default: info
  logs:
    custom_components.sun2: debug
```
With that enabled you should see messages like this in home-assistant.log every time the sensor updates:
```
2021-02-24 13:22:08 DEBUG (MainThread) [custom_components.sun2.sensor] Raw elevation = 36.643357 -> 36.6
```
When it fails do those messages stop, or do they keep coming but showing the same value?
