### ISSUE TITLE
No version not allowed by Home assistant

### ISSUE THREAD

**Issue by yfands** [pnbruckner/ha-sun2#30]
Hello Got a warning ...

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 11:16:04 (3 occurrences)
Last logged: 11:16:08

No 'version' key in the manifest file for custom integration 'sun2'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'sun2'

Regards Frank

**Comment by pnbruckner** [comment]
@yfands that was already addressed in the 1.8.2 release issued 4 days ago. Thanks!
