### ISSUE TITLE
sun2: Error on device update! From HA version 2021.5.0dev20210402

### ISSUE THREAD

**Issue by pbranly** [pnbruckner/ha-sun2#32]
I can’t use anymore this integration from this Dev version
Log is:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/config/custom_components/sun2/binary_sensor.py", line 284, in async_update
    cur_elev = astral_loc().solar_elevation(cur_dttm)
AttributeError: 'tuple' object has no attribute 'solar_elevation'
```
Regards

**Comment by pnbruckner** [comment]
Yep, looks like they upgraded the astral package from 1.10.1 to 2.2 and its API (as well as the API of `homeassistant.helpers.sun`) changed significantly. Argh! I'll guess I need to add this to my list of To Do's.

**Comment by pbranly** [comment]
Next core release will be next Wednesday 
This does not let you a lot of time 
Regards
Phil

**Comment by pnbruckner** [comment]
@pbranly, any chance you can test this PR? I tested it with the latest HA dev checkout, as well as 2021.3.4, and it seems to work for both.

**Comment by pbranly** [comment]
Sure i can.
Did you generate a beta version ? If yes, I will update with the beta option in HACS 
PPhil

**Comment by pnbruckner** [comment]
@pbranly, no, I don't officially support HACS anymore. Gave up a long time ago. Too much of a moving target. I'll just go ahead and make a release. If something comes up I'll try to fix it.

**Comment by pbranly** [comment]
I just tried to add your version but cannot with my IPad. For unknown reason I cannot make any modification from the IPad. 
i will try tomorrow from my PC
Regards
Phil

**Comment by pbranly** [comment]
It works .
Thanks
Philippe
