### ISSUE TITLE
Make avaliable to use own coordinates to track another sun

### ISSUE THREAD

**Issue by NoAdO** [pnbruckner/ha-sun2#36]
Please make it avaliable to use own coordinates to track another sun as a part of integration configuration. There's no simple way to track sun state in another town and at home location at one time.

**Comment by pnbruckner** [comment]
This might be relatively easy to add. I'll give it a shot. No promises. 😅

**Comment by pnbruckner** [comment]
@NoAdO I started working on it, and for the most part it was pretty straightforward. But there was one wrinkle. Specifically, what time zone should the date/time states and attributes be reported in? I.e., in HA's local time zone, or in the time zone of the other location? Until I hear back, I'll assume the other time zone.

And, just to be clear, you'll need to provide four pieces of data for the desired location: latitude, longitude, time zone and elevation. My integration will not try to determine time zone and elevation from the latitude & longitude (although, in theory, that should be possible.)

**Comment by NoAdO** [comment]
Sounds logical. Manual is manual. I use command line sensor to wget from open api for now to get time of sunrise and sunset and it is a strange solution - that's why i asked.
