### ISSUE TITLE
Enhancement Request: Date configuration/Next transition

### ISSUE THREAD

**Issue by LouPaloma** [pnbruckner/ha-sun2#44]
This is a nice bit of work!

Looking at your code I see that you are doing calculations for solar elevations in the future.  With that in mind could you:

1) Make a sensor configuration parameter of "date"?  That being tomorrow or some other day in the future, i.e., what time is sunrise tomorrow?  Ideally, this would be a date offset, e.g., "today + 1", "tomorrow"

2) My intent for this is to determine the next transition, i.e., if it's currently day time, the next transition will be "sunset" and it will happen in "hh:mm:ss"

Sadly, I'm not a Python programmer, so I can provide you with a code PR.

Thanks.

**Comment by pnbruckner** [comment]
@LouPaloma you can do that with the standard `sun.sun` integration and the following template:
```
{% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
{% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
{% set when = ([next_rising, next_setting]|min - now().timestamp())|timestamp_custom('%-H:%M:%S', false) %}
The sun will {{ 'rise' if next_rising < next_setting else 'set' }} in {{ when }}.
```
