### ISSUE TITLE
cannot import "astral_event"

### ISSUE THREAD

**Issue by Giuliointhetube** [pnbruckner/ha-sun2#45]
after upgrading to the new version (2.0.1) I get this error  from the configuration check

Platform error sensor.sun2 - cannot import name 'astral_event' from 'custom_components.sun2.helpers' (/config/custom_components/sun2/helpers.py)

**Comment by pnbruckner** [comment]
What version of HA Core are you using? What version of this custom component are you using? Have you restarted HA after upgrading to the latest versions?

This has been reported a few times, but in no case that I'm aware of, has the problem continued after upgrading HA Core & this custom component, and then restarting.
