### ISSUE TITLE
Since update to homeassitant core-2021.6.0 I get an error

### ISSUE THREAD

**Issue by sanderlv** [pnbruckner/ha-sun2#48]
Nothing changed only updated homeassistant.

![image](https://user-images.githubusercontent.com/16528916/120652836-70aa5080-c480-11eb-8d51-a9baba63070f.png)

![image](https://user-images.githubusercontent.com/16528916/120652990-90da0f80-c480-11eb-8c94-445fe01943f0.png)

might this have to do with the new "time format feature"?

**Comment by pnbruckner** [comment]
Did you update to the [latest release](https://github.com/pnbruckner/ha-sun2/releases/tag/2.0.2)?

**Comment by sanderlv** [comment]
Yes, that was it... any chance to integrate in HACS? I did not see it was updated.

**Comment by pnbruckner** [comment]
I understand you can add it as an external repo.
