### ISSUE TITLE
Request/Enhancement Sensor Daylight "actual_state"

### ISSUE THREAD

**Issue by n0nk** [pnbruckner/ha-sun2#58]
In the past i used Deconz addon, which provided Daylight sensor (as you know i guess...)
I searched for a replacement and found this. But i am missing a beloved feature :)

I don't want to work with several different sensors therefore it would be nice to have a actual_state sensor (i dont care for the naming)
which just shows the string of the actual Sun state depending on the calculations.

E.g.
sensor.sun2_actual_state = "solar_noon"
switch to
sensor.sun2_actual_state = "sunset"
switch to
sensor.sun2_actual_state = "dusk"
switch to ... etc.

Anyone else thinks that this may be useful?

Thanks in advance

**Comment by n0nk** [comment]
Actually it should behave like the existing sun.sun sensor but more detailled

**Comment by n0nk** [comment]
This is a screenshot of the Sensor history:
![a559159e0067ea157baeac16a93b7ec1cf513eb5_2_690x480](https://user-images.githubusercontent.com/51108634/158951198-4f9b4db1-c295-4eff-8693-04d64440da40.png)
And it showed changes the states and just keeps the last state it switched to. This was easy to use in automations while doing something like "Do something if daylight.state switched to Dusk" like using a motion sensor.
![b05ac02e69bd0202f6af824b4008c33e068e3786](https://user-images.githubusercontent.com/51108634/158951767-e9a2d700-b7b2-4985-b147-dd0a87adda97.png)
(Screenshots "stolen" from this thread because i am not running deconz anylonger --> https://community.home-assistant.io/t/sensor-daylight-in-automations/267560)

The Sensor got the following states:
<html>
<body>


sunrise_start | sunrise (top edge of the sun appears on the horizon)
-- | --
sunrise_end | sunrise ends (bottom edge of the sun touches the horizon)
golden_hour_1 | morning golden hour (soft light, the best time for photography)
solar_noon | solar noon (sun is in the highest position)
golden_hour_2 | evening golden hour
sunset_start | sunset starts (bottom edge of the sun touches the horizon)
sunset_end | sunset (sun disappears below the horizon, evening civil twilight starts)
dusk | dusk (evening nautical twilight starts)
nautical_dusk | nautical dusk (evening astronomical twilight starts)
night_start | night starts (dark enough for astronomical observations)
nadir | nadir (darkest moment of the night, the sun is in the lowest position)
night_end | night ends (morning astronomical twilight starts)
nautical_dawn | nautical dawn (morning nautical twilight starts)
dawn | dawn (morning nautical twilight ends, morning civil twilight starts)


</body>
</html>
(source: https://www.home-assistant.io/integrations/deconz/#deconz-daylight-sensor)

This sensor was the most useful sensor for my time/light-based automations :) Would be nice to get it back without deconz installation.

Does this answer your questions?

**Comment by pnbruckner** [comment]
Yes, it does, thanks! Those states seem kind of weird to me, and not very symmetric. But I suppose I could try to implement a "deCONZ Daylight Sensor" emulation sensor. No promises. I'll try to remember to comment here if/when I get working on it.

**Comment by n0nk** [comment]
Nice to read this. Thanks for trying :)

**Comment by pnbruckner** [comment]
After doing a bit of digging, I'm not 100% sure, because I don't know how to see the code of the actual deconz stuff, but based on what you've provided, and the code I could see, it appears the states of the sensor are effectively the name of the previous event. E.g., nadir starts at the lowest elevation (i.e., nadir) and continues until the sun reaches -18 degrees, which is the start of morning astronomical twilight. At that point the state changes to night_end and continues until the sun reaches -12 degrees, which is the start of morning nautical twilight.

Here are what I believe the states would be:

Sun Angle | Event | Period Begins | State Begins ???
-|-|-|-
lowest | nadir | (night continues) | nadir
-18 | astronomical dawn | morning astronomical twilight | night_end
-12 | nautical dawn | morning nautical twilight | nautical_dawn
-6 | civil dawn | morning civil twilight & golden hour 1 | dawn
-0.833 | sunrise | day (morning golden hour continues) | sunrise_start
-0.3 | - | (day & morning golden hour continue) | sunrise_end
6 | - | (day continues) | golden_hour_1
highest | solar noon | (day continues) | solar_noon
6 | - | night golden hour (day continues) | golden_hour_2
-0.3 | - | (day & night golden hour continue) | sunset_start
-0.833 | sunset | evening civil twilight | sunset_end
-6 | civil dusk | evening nautical twilight | dusk
-12 | nautical dusk | evening astronomical twilight | nautical_dusk
-18 | astronomical dusk | night | night_start

I'm not sure that makes perfect sense, but that's the best I can tell.

Let me know what you think.

**Comment by pnbruckner** [comment]
@n0nk I have an initial implementation that I'm testing out.

**Comment by n0nk** [comment]
@pnbruckner, 
Sorry for the delayed answer, i was on vacation. initial implementation good. If you want me to test or something else please let me know.

**Comment by n0nk** [comment]
> I don't know how to see the code of the actual deconz stuff
I dont know if you noticed, but the deconz sensor is based on this github project --> https://github.com/mourner/suncalc
Some states --> https://github.com/mourner/suncalc/blob/6bc2757074c1e5eaa2389aa2ab36806f04c6d2a0/suncalc.js#L102
So it seems to me that you picked the right states by sun angle :)

> ... it appears the states of the sensor are effectively the name of the previous event ...
that's also my understanding and how i used it. In automations i just checked the actual_state change event or checkd by time.

> Let me know what you think.

**Comment by pnbruckner** [comment]
I'm getting ready to check in the initial changes on a branch. I think it pretty much works, but I want to create a second option with states that I think make more sense, too. I need to massage the code a bit so both sensors can use the same code but with different data tables.

In any case, here's what the sensor looks like:

![image](https://user-images.githubusercontent.com/36015321/160683276-e0e6e8c4-a252-42cc-9c35-a9288762b5c4.png)

There are five instantiations, with locations that have the same longitude, but different latitudes: 80, 40, 0, -40 & -80. The top binary sensors are template sensors that show the value of the `daylight` attribute of the five phase sensors.

**Comment by pnbruckner** [comment]
> I dont know if you noticed, but the deconz sensor is based on this github project --> https://github.com/mourner/suncalc
Some states --> https://github.com/mourner/suncalc/blob/6bc2757074c1e5eaa2389aa2ab36806f04c6d2a0/suncalc.js#L102

Yes, I've seen that, and I've seen HA's deCONZ integration code, but not the code in the middle -- i.e., not the actual deCONZ code itself, so I don't know how it takes the results from the suncalc library and translates that into states.

**Comment by n0nk** [comment]
> In any case, here's what the sensor looks like:
Actually that looks great for me 🥇 

>... but not the code in the middle ...
Maybe this is the missing part? --> https://github.com/dresden-elektronik/deconz-rest-plugin/blob/ffda04e41a56947cf1aa0db53f98111bfdc4438c/daylight.cpp#L70

**Comment by pnbruckner** [comment]
Ah, thanks. I didn't try to find the deCONZ software, but that looks like it. And, yes, it does look like it's a port of the suncalc package. It did say "based on", which I took to mean "uses", but I guess it really meant "ported." 😄

**Comment by pnbruckner** [comment]
Ok, I looked at [pydeconz](https://github.com/Kane610/deconz/tree/v87/pydeconz) & [deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/tree/stable), and everything I've done so far seems right, except for the `daylight` attribute. Despite the description on the [HA deCONZ Daylight Sensor doc page](https://www.home-assistant.io/integrations/deconz/#deconz-daylight-sensor), the `daylight` attribute is true between sunrise and sunset, which of course, makes more sense. I'll update accordingly.

**Comment by n0nk** [comment]
At first i also assumed they used it as a lib. I am happy to "help" you.

**Comment by n0nk** [comment]
Maybe you could tag the actual branch version as 2.x.x-b1 and prerelease it so i maybe would be able to add it direcly using hacs. ... At least i guess this should also work with branches but didn't find in die docs.
