### ISSUE TITLE
HACS integration

### ISSUE THREAD

**Issue by n0nk** [pnbruckner/ha-sun2#59]
Hi,

I got another small "issue":

I installed ha-sun2 using HACS and just noticed that there is no description on your repository due to a missing hacs.json (with at least "render_readme": true)
Maybe you are interested in adding this https://hacs.xyz/docs/publish/start#hacsjson

**Comment by pnbruckner** [comment]
If you check the closed issues for any of my custom integrations, you will see that I gave up trying to keep up with HACS, & its predecessors, long ago. In my experience, it's been a constantly moving target. So, no, thank you.

**Comment by n0nk** [comment]
ah okay, i didn't see this. But i understand.
