### ISSUE TITLE
I can't install sun2

### ISSUE THREAD

**Issue by OM-3kChcBjgFR2COfP** [pnbruckner/ha-sun2#66]
I can't install sun2 using hacs...I copied it to /hassio/homeassistant/custom_components folder, but sun2 is not in the hacs list, what am I doing wrong?

**Comment by pnbruckner** [comment]
Did you read and follow the [HACS installation instructions](https://github.com/pnbruckner/ha-sun2#with-hacs)?

It sounds like you performed the [manual installation](https://github.com/pnbruckner/ha-sun2#manual), in which case you don't need HACS, you can just add your desired sun2 configuration and it should work.

But, if you're using HACS, it's probably better to install that way so you can get automatic update notices.
