### ISSUE TITLE
Automation based on rising attribute fails

### ISSUE THREAD

**Issue by randomhammer** [pnbruckner/ha-sun2#67]
I have a really strange problem. I have an integration that has a condition that checks the rising attribute of the sun_phase sensor for rising is false. For some reason it always fails. Below is a capture of the condition:
<img width="554" alt="Screen Shot 2022-08-24 at 8 26 09 PM" src="https://user-images.githubusercontent.com/12021759/186553501-3478ea4f-6e5e-4fb3-8ffa-ac3793b610dd.png">

And here is a capture of the current state of the sensor:

<img width="1008" alt="Screen Shot 2022-08-24 at 8 26 23 PM" src="https://user-images.githubusercontent.com/12021759/186553546-eb3bc1b5-078e-4842-9e2a-a53c31f354a3.png">

I must missing something simple, but the condition fails and the automation never fires, even though the attribute rising is false. 

Any clue what I am doing wrong?

**Comment by pnbruckner** [comment]
I think you're being bit by a limitation in the UI. It only accepts strings for values, but the attribute is a boolean, and false as a string does not match false as a boolean.

You can work around this limitation by editing that condition in YAML mode. Then change the line:
```yaml
state: "false"
```
to:
```yaml
state: false
```

**Comment by karaminder** [comment]
Ah, this was the solution I needed.
