### ISSUE TITLE
HACS installation not working

### ISSUE THREAD

**Issue by airbone42** [pnbruckner/ha-sun2#70]
Hi,

I tried to install the integration via HACS by addint the custom repository as described. It's then listed as imported repo, but even after a HA restart there's no new "sun2" integration available to add in HA.

Unfortunately, also the logs didn't output any error related to this. Is there anything else that could be checked?

Thanks in advance.

**Comment by pnbruckner** [comment]
Sorry, I don't officially support HACS. I try to make this repo compatible with HACS, but I don't use HACS myself or attempt to make sure my custom integrations work with it. It's a long story I won't go into here. However, I know many people have had success installing my custom integration via HACS, so unless something has recently changed in HACS, it should work. But beyond that, I can't really help.

**Comment by pnbruckner** [comment]
You could try asking for help here from other users who have been able to install this custom integration via HACS:

https://community.home-assistant.io/t/enhanced-sun-component/63553

**Comment by pnbruckner** [comment]
FWIW, HACS support was improved in the 2.2.0 release.
