### ISSUE TITLE
astral V. 3.2 - Moon data

### ISSUE THREAD

**Issue by Tom-ahawk** [pnbruckner/ha-sun2#71]
Looks like the package now has the calculations for
Moon rise, set, azimuth and zenith.

https://pypi.org/project/astral/1.2/#history

Any chance you can enhance your Sun2 with a moon sensor with state like on/off or up/ down and attributes for the rest of the moon data?

Maybe appropriate to rename the integration to Sun and Moon.

**Comment by pnbruckner** [comment]
Those values were introduced in the astral package starting with the [3.0 release](https://sffjunkie.github.io/astral/#version-history). HA (and hence this custom integration) uses astral package version 2.2. In the 2.2 release, the only moon related value is [phase](https://sffjunkie.github.io/astral/#phase).

**Comment by Tom-ahawk** [comment]
Then maybe sometimes in the far future... :  )
