### ISSUE TITLE
This entity is no longer being provided by the sun2 integration. If the entity is no longer in use, delete it in settings.

### ISSUE THREAD

**Issue by airbone42** [pnbruckner/ha-sun2#80]
I just upgraded from a 2022 HA version to 2023.4.6, but since the upgrade all sun2 entities show that same error. Is it somehow possible to use the integration also with the latest HA version? As especially the sun phase entity was very helpful to control shutters, lights etc.

**Comment by pnbruckner** [comment]
What version of this custom integration are you using?

I'm running HA version 2023.4.5 and I'm not seeing those (or any) errors. I suppose it's possible something changed in 2023.4.6 to break this. I can try testing with that version later.

Can you provide your current sun2 configuration?
