### ISSUE TITLE
No more Astronomical Dawn and Astronomical Dusk?

### ISSUE THREAD

**Issue by Mellowlynx** [pnbruckner/ha-sun2#82]
Hi there, when adding Astronomical Dawn and Astronomical Dusk
I get a error that the entity is no longer being provided by the sun2.
Is this permanent, a bug or something else?
It's still in the documentation so hoped to use it.

![image](https://github.com/pnbruckner/ha-sun2/assets/2348339/dfb9f03b-8217-4d35-99ba-8c2f4d347a5c)

**Comment by pnbruckner** [comment]
What version of HA are you using, and what version of this integration are you using? Have you upgraded either recently?

Please share you sun2 configuration.

That message just means that then the particular entity ID no longer exists in your system. Did you change the `entity_namespace` for the sun2 configuration? Have you checked the STATES tab (under Developer Tools) to see if the entity exists with a different entity ID?

Are there any related error messages?

**Comment by Mellowlynx** [comment]
I.m running:
  Home Assistant 2023.5.3
  Supervisor 2023.04.1
  Operating System 10.1
  Frontend 20230503.3 - latest

Sun2: V 2.2.1

I did not change the `entity_namespace` as far as I know.
I also do not have any other error messages.

In STATES I see:
![image](https://github.com/pnbruckner/ha-sun2/assets/2348339/4a1b8dd1-63ac-44f8-9774-2050b16449dc)

As a test I added all Sun2 censors yesterday by copying them from the Example Full Configuration.
`sensor sun2:
  - platform: sun2
    entity_namespace: Balk
    latitude: 52.896875
    longitude: 5.578475
    time_zone: Europe/Brussels
    elevation: 3
    monitored_conditions:
      - solar_midnight
      - astronomical_dawn
      - nautical_dawn
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - nautical_dusk
      - astronomical_dusk
      - daylight
      - civil_daylight
      - nautical_daylight
      - astronomical_daylight
      - night
      - civil_night
      - nautical_night
      - astronomical_night
      - elevation
      - min_elevation
      - max_elevation
      - sun_phase
      - deconz_daylight`

Hope this helps.

**Comment by pnbruckner** [comment]
No, unfortunately, that doesn't really help.

First, try removing the entity mentioned in the message above, and any others that are similar.

Next, try enabling debug for the sun2 integration. Then, after restarting HA, search the log for any sun2 related messages. Share what you find.

**Comment by Mellowlynx** [comment]
I can't remove them all probably because they are in use,

I could remove the non working once and hope this will do.

I fount this real error in the logs when looking for sun2

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:532
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 5:26:18 PM (2 occurrences)
Last logged: 5:26:18 PM

Error adding entities for domain sensor with platform sun2
Error while setting up sun2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 521, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 532, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.balk_astronomical_dawn has timestamp device class but provides state none:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''`

The other mentions look normal,
update check, Getting repository information and  2x a Registered new sensor.sun2 entity.

In the entity list the status of the added entitys is restored.

Please let me know if you need more.

**Comment by Mellowlynx** [comment]
I also tried to edit the `entity_namespace` to something random and restarted HA.
Same thing, everything else is fine, just the 4 Astronomical entity's that have unknown as data or are unavailable.

Same error as above.

**Comment by pnbruckner** [comment]
Thanks. That gives me something to look into. Probably the core team changed something again and I have to figure out how to deal with the change. I'll try to find time to work on this soon.

**Comment by pnbruckner** [comment]
I believe this issue has been around for at least a couple of years. But given the conditions that are required to trigger the error, I've never seen it myself, and so far, nobody else has reported it.

If the location and time of year is such that the associated event does not happen, then the sensor's state is supposed to be the string value "none". (E.g., you are probably located far enough north or south to be close enough to the poles such that at this time of year there is no Astronomical Dawn or Dusk.) However, given the way the core software works, a sensor with a device class of timestamp (which this one has) is apparently not allowed to have that state. It must either be the Python None value (which gets shown in the UI as "unknown"), or a Python datetime with a time zone. This requirement was added at least as far back as v2021.12.

I have to think a bit about the best way to handle this. I can either attempt to bypass the checks that raise the error, or I can give in and just let the state be None (aka unknown.) Or, another possibility is, to make the state Unavailable, which may be the best compromise. But, making it Unavailable has some other side effects which I have to think through first.

In any case, I should be able to provide a fix before too long.

Thanks for reporting this!

**Comment by pnbruckner** [comment]
@Mellowlynx if you're comfortable modifying the custom integration code, I can suggest a change as a temporary workaround (which might become the actual fix), to at least see if the errors would go away, and hence, confirm the root cause.

In custom_components/sun2/sensor.py, comment out, or remove, the following block of code:

https://github.com/pnbruckner/ha-sun2/blob/c3176a0d37e0d2c8f2f5c59e573dc99d9a73dd4c/custom_components/sun2/sensor.py#L177-L183

This is the code that changes the state from the Python None value to the string value "none". Removing it leaves the state as None, which again, will show up in the UI as "unknown". And it will also (or, at least, should) prevent the errors you were seeing. If you try this, let me know how it goes.

**Comment by Mellowlynx** [comment]
@pnbruckner Thanks for your replays and explanation.

I commented out the code and indeed no error and in the UI it's unknown now without the error.
Good to know that's not my setup but might be my location (Netherlands)
In my lights setup I use `nautical_dusk` now and it's doing the job fine. so I'm good :)

Thanks so match for your time.
