### ISSUE TITLE
Can not add repo in HACS

### ISSUE THREAD

**Issue by RaptorPR443** [pnbruckner/ha-sun2#84]
Hello,

when trying to add the repo to HACS says the following error: <Plugin pnbruckner/ha-sun2> Repository structure for 2.2.2 is not compliant

**Comment by pnbruckner** [comment]
Have you followed the instructions here: https://hacs.xyz/docs/faq/custom_repositories/

What URL did you use for this integration? It should be https://github.com/pnbruckner/ha-sun2. Also, did you select integration for category?

**Comment by pnbruckner** [comment]
@RaptorPR443 is this still an issue? Any further details?

**Comment by pnbruckner** [comment]
Closing this due to no response from @RaptorPR443. Also, I was recently able to add it via HACS.
